spring:
  application:
    name: ${INFRAPILOT_APP_NAME:InfraPilot}

  lifecycle:
    timeout-per-shutdown-phase: 30s
  main:
    banner-mode: "off"

server:
  shutdown: graceful
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: true
        secure: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState
    metrics:
      enabled: true


info:
  app:
    name: ${INFRAPILOT_APP_NAME:InfraPilot}
    version: ${INFRAPILOT_APP_VERSION:0.0.0}
    commit: ${INFRAPILOT_GIT_COMMIT_SHA:unknown}
    build-timestamp: ${INFRAPILOT_BUILD_TIMESTAMP:unknown}

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%-5level service=InfraPilot correlationId=%X{correlationId:-} logger=%logger{36} message=%msg%n%ex{short}"
  level:
    root: INFO
    com.sumitverma.infrapilot: INFO

infrapilot:
  app-name: ${INFRAPILOT_APP_NAME:InfraPilot}
  app-version: ${INFRAPILOT_APP_VERSION:unknown}
  git-commit-sha: ${INFRAPILOT_GIT_COMMIT_SHA:unknown}
  build-timestamp: ${INFRAPILOT_BUILD_TIMESTAMP:unknown}
  hostname: ${HOSTNAME:unknown}
  environment: ${SPRING_PROFILES_ACTIVE:default}